
-- post
drop table if exists post;

drop table if exists author;

create table author(
                      id int generated by default as identity primary key,
                      first_name varchar(255) not null,
                      last_name varchar(255) not null,
                      email varchar(255) ,
                      username varchar(255) not null
);

create table post (
                  id int generated by default as identity primary key,
                  version int,
                  title varchar(255) not null,
                  content clob not null,
                  created_at timestamp default current_timestamp not null,
                  updated_at timestamp,
                  author int,
                  foreign key (author) references author(id)
);

create table comment(
    name varchar(255) not null,
    content varchar(255) not null,
    published_at timestamp default current_timestamp not null,
    updated_at timestamp,
    post int,
    foreign key (post) references post(id)
)